name: pragmatic_flutter
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^0.12.0+4

#  flutter_html: ^0.11.1

  #To open web reader link and buylink from BookDetailsPage
  url_launcher: ^5.4.11

  #Provider package
  provider:  #^4.3.2

  #flutter_bloc package
  flutter_bloc: ^6.0.1

  #SharedPreference-persisting theme selection
  shared_preferences: ^0.5.8

  #Moor plugin- Persisting theme selection
  moor: ^3.3.1
  sqlite3_flutter_libs: ^0.2.0
  # Helper to find the database path on mobile
  path_provider: ^1.6.11
  path: ^1.7.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

  #Flutter Icons
  font_awesome_flutter: ^8.8.1

  # Chapter08
  animated_floatactionbuttons: ^0.1.0
  syntax_highlighter: ^0.1.0

  # Chapter15 (launcher icons for BooksApp)
  flutter_launcher_icons: ^0.8.1

dev_dependencies:
  #Integration Testing
  flutter_driver:
    sdk: flutter

  #Widget Testing
  flutter_test:
    sdk: flutter

  #Unit Testing
  test: ^1.15.3

  #Generates files using Dart code.
  build_runner: ^1.10.2

  #This generator library turns Table classes from moor into database code.
  moor_generator: ^3.3.1


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/book_cover.png
     - assets/flutter_icon.png
     - lib/chapter06/widgets/
     - lib/chapter07/layouts/single/
     - lib/chapter07/layouts/multi/
     - lib/chapter08/layouts/

  fonts:
    - family: Pangolin
      fonts:
        - asset: assets/fonts/Pangolin-Regular.ttf

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/launcher/app_logo.png"
  image_path_android: "assets/launcher/app_logo.png"
  adaptive_icon_background: "assets/launcher/app_logo_background.png"
  adaptive_icon_foreground: "assets/launcher/app_logo.png"


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
